<?xml version="1.0" encoding="UTF-8" ?>
<Package name="getCameraImages" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="BdfFontFile" src="PIL/BdfFontFile.py" />
        <File name="BdfFontFile" src="PIL/BdfFontFile.pyc" />
        <File name="BlpImagePlugin" src="PIL/BlpImagePlugin.py" />
        <File name="BlpImagePlugin" src="PIL/BlpImagePlugin.pyc" />
        <File name="BmpImagePlugin" src="PIL/BmpImagePlugin.py" />
        <File name="BmpImagePlugin" src="PIL/BmpImagePlugin.pyc" />
        <File name="BufrStubImagePlugin" src="PIL/BufrStubImagePlugin.py" />
        <File name="BufrStubImagePlugin" src="PIL/BufrStubImagePlugin.pyc" />
        <File name="ContainerIO" src="PIL/ContainerIO.py" />
        <File name="ContainerIO" src="PIL/ContainerIO.pyc" />
        <File name="CurImagePlugin" src="PIL/CurImagePlugin.py" />
        <File name="CurImagePlugin" src="PIL/CurImagePlugin.pyc" />
        <File name="DcxImagePlugin" src="PIL/DcxImagePlugin.py" />
        <File name="DcxImagePlugin" src="PIL/DcxImagePlugin.pyc" />
        <File name="DdsImagePlugin" src="PIL/DdsImagePlugin.py" />
        <File name="DdsImagePlugin" src="PIL/DdsImagePlugin.pyc" />
        <File name="EpsImagePlugin" src="PIL/EpsImagePlugin.py" />
        <File name="EpsImagePlugin" src="PIL/EpsImagePlugin.pyc" />
        <File name="ExifTags" src="PIL/ExifTags.py" />
        <File name="ExifTags" src="PIL/ExifTags.pyc" />
        <File name="FitsStubImagePlugin" src="PIL/FitsStubImagePlugin.py" />
        <File name="FitsStubImagePlugin" src="PIL/FitsStubImagePlugin.pyc" />
        <File name="FliImagePlugin" src="PIL/FliImagePlugin.py" />
        <File name="FliImagePlugin" src="PIL/FliImagePlugin.pyc" />
        <File name="FontFile" src="PIL/FontFile.py" />
        <File name="FontFile" src="PIL/FontFile.pyc" />
        <File name="FpxImagePlugin" src="PIL/FpxImagePlugin.py" />
        <File name="FpxImagePlugin" src="PIL/FpxImagePlugin.pyc" />
        <File name="FtexImagePlugin" src="PIL/FtexImagePlugin.py" />
        <File name="FtexImagePlugin" src="PIL/FtexImagePlugin.pyc" />
        <File name="GbrImagePlugin" src="PIL/GbrImagePlugin.py" />
        <File name="GbrImagePlugin" src="PIL/GbrImagePlugin.pyc" />
        <File name="GdImageFile" src="PIL/GdImageFile.py" />
        <File name="GdImageFile" src="PIL/GdImageFile.pyc" />
        <File name="GifImagePlugin" src="PIL/GifImagePlugin.py" />
        <File name="GifImagePlugin" src="PIL/GifImagePlugin.pyc" />
        <File name="GimpGradientFile" src="PIL/GimpGradientFile.py" />
        <File name="GimpGradientFile" src="PIL/GimpGradientFile.pyc" />
        <File name="GimpPaletteFile" src="PIL/GimpPaletteFile.py" />
        <File name="GimpPaletteFile" src="PIL/GimpPaletteFile.pyc" />
        <File name="GribStubImagePlugin" src="PIL/GribStubImagePlugin.py" />
        <File name="GribStubImagePlugin" src="PIL/GribStubImagePlugin.pyc" />
        <File name="Hdf5StubImagePlugin" src="PIL/Hdf5StubImagePlugin.py" />
        <File name="Hdf5StubImagePlugin" src="PIL/Hdf5StubImagePlugin.pyc" />
        <File name="IcnsImagePlugin" src="PIL/IcnsImagePlugin.py" />
        <File name="IcnsImagePlugin" src="PIL/IcnsImagePlugin.pyc" />
        <File name="IcoImagePlugin" src="PIL/IcoImagePlugin.py" />
        <File name="IcoImagePlugin" src="PIL/IcoImagePlugin.pyc" />
        <File name="ImImagePlugin" src="PIL/ImImagePlugin.py" />
        <File name="ImImagePlugin" src="PIL/ImImagePlugin.pyc" />
        <File name="Image" src="PIL/Image.py" />
        <File name="Image" src="PIL/Image.pyc" />
        <File name="ImageChops" src="PIL/ImageChops.py" />
        <File name="ImageChops" src="PIL/ImageChops.pyc" />
        <File name="ImageCms" src="PIL/ImageCms.py" />
        <File name="ImageCms" src="PIL/ImageCms.pyc" />
        <File name="ImageColor" src="PIL/ImageColor.py" />
        <File name="ImageColor" src="PIL/ImageColor.pyc" />
        <File name="ImageDraw" src="PIL/ImageDraw.py" />
        <File name="ImageDraw" src="PIL/ImageDraw.pyc" />
        <File name="ImageDraw2" src="PIL/ImageDraw2.py" />
        <File name="ImageDraw2" src="PIL/ImageDraw2.pyc" />
        <File name="ImageEnhance" src="PIL/ImageEnhance.py" />
        <File name="ImageEnhance" src="PIL/ImageEnhance.pyc" />
        <File name="ImageFile" src="PIL/ImageFile.py" />
        <File name="ImageFile" src="PIL/ImageFile.pyc" />
        <File name="ImageFilter" src="PIL/ImageFilter.py" />
        <File name="ImageFilter" src="PIL/ImageFilter.pyc" />
        <File name="ImageFont" src="PIL/ImageFont.py" />
        <File name="ImageFont" src="PIL/ImageFont.pyc" />
        <File name="ImageGrab" src="PIL/ImageGrab.py" />
        <File name="ImageGrab" src="PIL/ImageGrab.pyc" />
        <File name="ImageMath" src="PIL/ImageMath.py" />
        <File name="ImageMath" src="PIL/ImageMath.pyc" />
        <File name="ImageMode" src="PIL/ImageMode.py" />
        <File name="ImageMode" src="PIL/ImageMode.pyc" />
        <File name="ImageMorph" src="PIL/ImageMorph.py" />
        <File name="ImageMorph" src="PIL/ImageMorph.pyc" />
        <File name="ImageOps" src="PIL/ImageOps.py" />
        <File name="ImageOps" src="PIL/ImageOps.pyc" />
        <File name="ImagePalette" src="PIL/ImagePalette.py" />
        <File name="ImagePalette" src="PIL/ImagePalette.pyc" />
        <File name="ImagePath" src="PIL/ImagePath.py" />
        <File name="ImagePath" src="PIL/ImagePath.pyc" />
        <File name="ImageQt" src="PIL/ImageQt.py" />
        <File name="ImageQt" src="PIL/ImageQt.pyc" />
        <File name="ImageSequence" src="PIL/ImageSequence.py" />
        <File name="ImageSequence" src="PIL/ImageSequence.pyc" />
        <File name="ImageShow" src="PIL/ImageShow.py" />
        <File name="ImageShow" src="PIL/ImageShow.pyc" />
        <File name="ImageStat" src="PIL/ImageStat.py" />
        <File name="ImageStat" src="PIL/ImageStat.pyc" />
        <File name="ImageTk" src="PIL/ImageTk.py" />
        <File name="ImageTk" src="PIL/ImageTk.pyc" />
        <File name="ImageTransform" src="PIL/ImageTransform.py" />
        <File name="ImageTransform" src="PIL/ImageTransform.pyc" />
        <File name="ImageWin" src="PIL/ImageWin.py" />
        <File name="ImageWin" src="PIL/ImageWin.pyc" />
        <File name="ImtImagePlugin" src="PIL/ImtImagePlugin.py" />
        <File name="ImtImagePlugin" src="PIL/ImtImagePlugin.pyc" />
        <File name="IptcImagePlugin" src="PIL/IptcImagePlugin.py" />
        <File name="IptcImagePlugin" src="PIL/IptcImagePlugin.pyc" />
        <File name="Jpeg2KImagePlugin" src="PIL/Jpeg2KImagePlugin.py" />
        <File name="Jpeg2KImagePlugin" src="PIL/Jpeg2KImagePlugin.pyc" />
        <File name="JpegImagePlugin" src="PIL/JpegImagePlugin.py" />
        <File name="JpegImagePlugin" src="PIL/JpegImagePlugin.pyc" />
        <File name="JpegPresets" src="PIL/JpegPresets.py" />
        <File name="JpegPresets" src="PIL/JpegPresets.pyc" />
        <File name="McIdasImagePlugin" src="PIL/McIdasImagePlugin.py" />
        <File name="McIdasImagePlugin" src="PIL/McIdasImagePlugin.pyc" />
        <File name="MicImagePlugin" src="PIL/MicImagePlugin.py" />
        <File name="MicImagePlugin" src="PIL/MicImagePlugin.pyc" />
        <File name="MpegImagePlugin" src="PIL/MpegImagePlugin.py" />
        <File name="MpegImagePlugin" src="PIL/MpegImagePlugin.pyc" />
        <File name="MpoImagePlugin" src="PIL/MpoImagePlugin.py" />
        <File name="MpoImagePlugin" src="PIL/MpoImagePlugin.pyc" />
        <File name="MspImagePlugin" src="PIL/MspImagePlugin.py" />
        <File name="MspImagePlugin" src="PIL/MspImagePlugin.pyc" />
        <File name="PSDraw" src="PIL/PSDraw.py" />
        <File name="PSDraw" src="PIL/PSDraw.pyc" />
        <File name="PaletteFile" src="PIL/PaletteFile.py" />
        <File name="PaletteFile" src="PIL/PaletteFile.pyc" />
        <File name="PalmImagePlugin" src="PIL/PalmImagePlugin.py" />
        <File name="PalmImagePlugin" src="PIL/PalmImagePlugin.pyc" />
        <File name="PcdImagePlugin" src="PIL/PcdImagePlugin.py" />
        <File name="PcdImagePlugin" src="PIL/PcdImagePlugin.pyc" />
        <File name="PcfFontFile" src="PIL/PcfFontFile.py" />
        <File name="PcfFontFile" src="PIL/PcfFontFile.pyc" />
        <File name="PcxImagePlugin" src="PIL/PcxImagePlugin.py" />
        <File name="PcxImagePlugin" src="PIL/PcxImagePlugin.pyc" />
        <File name="PdfImagePlugin" src="PIL/PdfImagePlugin.py" />
        <File name="PdfImagePlugin" src="PIL/PdfImagePlugin.pyc" />
        <File name="PdfParser" src="PIL/PdfParser.py" />
        <File name="PdfParser" src="PIL/PdfParser.pyc" />
        <File name="PixarImagePlugin" src="PIL/PixarImagePlugin.py" />
        <File name="PixarImagePlugin" src="PIL/PixarImagePlugin.pyc" />
        <File name="PngImagePlugin" src="PIL/PngImagePlugin.py" />
        <File name="PngImagePlugin" src="PIL/PngImagePlugin.pyc" />
        <File name="PpmImagePlugin" src="PIL/PpmImagePlugin.py" />
        <File name="PpmImagePlugin" src="PIL/PpmImagePlugin.pyc" />
        <File name="PsdImagePlugin" src="PIL/PsdImagePlugin.py" />
        <File name="PsdImagePlugin" src="PIL/PsdImagePlugin.pyc" />
        <File name="PyAccess" src="PIL/PyAccess.py" />
        <File name="PyAccess" src="PIL/PyAccess.pyc" />
        <File name="SgiImagePlugin" src="PIL/SgiImagePlugin.py" />
        <File name="SgiImagePlugin" src="PIL/SgiImagePlugin.pyc" />
        <File name="SpiderImagePlugin" src="PIL/SpiderImagePlugin.py" />
        <File name="SpiderImagePlugin" src="PIL/SpiderImagePlugin.pyc" />
        <File name="SunImagePlugin" src="PIL/SunImagePlugin.py" />
        <File name="SunImagePlugin" src="PIL/SunImagePlugin.pyc" />
        <File name="TarIO" src="PIL/TarIO.py" />
        <File name="TarIO" src="PIL/TarIO.pyc" />
        <File name="TgaImagePlugin" src="PIL/TgaImagePlugin.py" />
        <File name="TgaImagePlugin" src="PIL/TgaImagePlugin.pyc" />
        <File name="TiffImagePlugin" src="PIL/TiffImagePlugin.py" />
        <File name="TiffImagePlugin" src="PIL/TiffImagePlugin.pyc" />
        <File name="TiffTags" src="PIL/TiffTags.py" />
        <File name="TiffTags" src="PIL/TiffTags.pyc" />
        <File name="WalImageFile" src="PIL/WalImageFile.py" />
        <File name="WalImageFile" src="PIL/WalImageFile.pyc" />
        <File name="WebPImagePlugin" src="PIL/WebPImagePlugin.py" />
        <File name="WebPImagePlugin" src="PIL/WebPImagePlugin.pyc" />
        <File name="WmfImagePlugin" src="PIL/WmfImagePlugin.py" />
        <File name="WmfImagePlugin" src="PIL/WmfImagePlugin.pyc" />
        <File name="XVThumbImagePlugin" src="PIL/XVThumbImagePlugin.py" />
        <File name="XVThumbImagePlugin" src="PIL/XVThumbImagePlugin.pyc" />
        <File name="XbmImagePlugin" src="PIL/XbmImagePlugin.py" />
        <File name="XbmImagePlugin" src="PIL/XbmImagePlugin.pyc" />
        <File name="XpmImagePlugin" src="PIL/XpmImagePlugin.py" />
        <File name="XpmImagePlugin" src="PIL/XpmImagePlugin.pyc" />
        <File name="__init__" src="PIL/__init__.py" />
        <File name="__init__" src="PIL/__init__.pyc" />
        <File name="__main__" src="PIL/__main__.py" />
        <File name="__main__" src="PIL/__main__.pyc" />
        <File name="_binary" src="PIL/_binary.py" />
        <File name="_binary" src="PIL/_binary.pyc" />
        <File name="_imaging" src="PIL/_imaging.pyd" />
        <File name="_imagingcms" src="PIL/_imagingcms.pyd" />
        <File name="_imagingft" src="PIL/_imagingft.pyd" />
        <File name="_imagingmath" src="PIL/_imagingmath.pyd" />
        <File name="_imagingmorph" src="PIL/_imagingmorph.pyd" />
        <File name="_imagingtk" src="PIL/_imagingtk.pyd" />
        <File name="_tkinter_finder" src="PIL/_tkinter_finder.py" />
        <File name="_tkinter_finder" src="PIL/_tkinter_finder.pyc" />
        <File name="_util" src="PIL/_util.py" />
        <File name="_util" src="PIL/_util.pyc" />
        <File name="_version" src="PIL/_version.py" />
        <File name="_version" src="PIL/_version.pyc" />
        <File name="_webp" src="PIL/_webp.pyd" />
        <File name="features" src="PIL/features.py" />
        <File name="features" src="PIL/features.pyc" />
        <File name="INSTALLER" src="Pillow-6.2.2.dist-info/INSTALLER" />
        <File name="LICENSE" src="Pillow-6.2.2.dist-info/LICENSE" />
        <File name="METADATA" src="Pillow-6.2.2.dist-info/METADATA" />
        <File name="RECORD" src="Pillow-6.2.2.dist-info/RECORD" />
        <File name="WHEEL" src="Pillow-6.2.2.dist-info/WHEEL" />
        <File name="top_level" src="Pillow-6.2.2.dist-info/top_level.txt" />
        <File name="zip-safe" src="Pillow-6.2.2.dist-info/zip-safe" />
        <File name="BdfFontFile" src="libs/PIL/BdfFontFile.py" />
        <File name="BdfFontFile" src="libs/PIL/BdfFontFile.pyc" />
        <File name="BlpImagePlugin" src="libs/PIL/BlpImagePlugin.py" />
        <File name="BlpImagePlugin" src="libs/PIL/BlpImagePlugin.pyc" />
        <File name="BmpImagePlugin" src="libs/PIL/BmpImagePlugin.py" />
        <File name="BmpImagePlugin" src="libs/PIL/BmpImagePlugin.pyc" />
        <File name="BufrStubImagePlugin" src="libs/PIL/BufrStubImagePlugin.py" />
        <File name="BufrStubImagePlugin" src="libs/PIL/BufrStubImagePlugin.pyc" />
        <File name="ContainerIO" src="libs/PIL/ContainerIO.py" />
        <File name="ContainerIO" src="libs/PIL/ContainerIO.pyc" />
        <File name="CurImagePlugin" src="libs/PIL/CurImagePlugin.py" />
        <File name="CurImagePlugin" src="libs/PIL/CurImagePlugin.pyc" />
        <File name="DcxImagePlugin" src="libs/PIL/DcxImagePlugin.py" />
        <File name="DcxImagePlugin" src="libs/PIL/DcxImagePlugin.pyc" />
        <File name="DdsImagePlugin" src="libs/PIL/DdsImagePlugin.py" />
        <File name="DdsImagePlugin" src="libs/PIL/DdsImagePlugin.pyc" />
        <File name="EpsImagePlugin" src="libs/PIL/EpsImagePlugin.py" />
        <File name="EpsImagePlugin" src="libs/PIL/EpsImagePlugin.pyc" />
        <File name="ExifTags" src="libs/PIL/ExifTags.py" />
        <File name="ExifTags" src="libs/PIL/ExifTags.pyc" />
        <File name="FitsStubImagePlugin" src="libs/PIL/FitsStubImagePlugin.py" />
        <File name="FitsStubImagePlugin" src="libs/PIL/FitsStubImagePlugin.pyc" />
        <File name="FliImagePlugin" src="libs/PIL/FliImagePlugin.py" />
        <File name="FliImagePlugin" src="libs/PIL/FliImagePlugin.pyc" />
        <File name="FontFile" src="libs/PIL/FontFile.py" />
        <File name="FontFile" src="libs/PIL/FontFile.pyc" />
        <File name="FpxImagePlugin" src="libs/PIL/FpxImagePlugin.py" />
        <File name="FpxImagePlugin" src="libs/PIL/FpxImagePlugin.pyc" />
        <File name="FtexImagePlugin" src="libs/PIL/FtexImagePlugin.py" />
        <File name="FtexImagePlugin" src="libs/PIL/FtexImagePlugin.pyc" />
        <File name="GbrImagePlugin" src="libs/PIL/GbrImagePlugin.py" />
        <File name="GbrImagePlugin" src="libs/PIL/GbrImagePlugin.pyc" />
        <File name="GdImageFile" src="libs/PIL/GdImageFile.py" />
        <File name="GdImageFile" src="libs/PIL/GdImageFile.pyc" />
        <File name="GifImagePlugin" src="libs/PIL/GifImagePlugin.py" />
        <File name="GifImagePlugin" src="libs/PIL/GifImagePlugin.pyc" />
        <File name="GimpGradientFile" src="libs/PIL/GimpGradientFile.py" />
        <File name="GimpGradientFile" src="libs/PIL/GimpGradientFile.pyc" />
        <File name="GimpPaletteFile" src="libs/PIL/GimpPaletteFile.py" />
        <File name="GimpPaletteFile" src="libs/PIL/GimpPaletteFile.pyc" />
        <File name="GribStubImagePlugin" src="libs/PIL/GribStubImagePlugin.py" />
        <File name="GribStubImagePlugin" src="libs/PIL/GribStubImagePlugin.pyc" />
        <File name="Hdf5StubImagePlugin" src="libs/PIL/Hdf5StubImagePlugin.py" />
        <File name="Hdf5StubImagePlugin" src="libs/PIL/Hdf5StubImagePlugin.pyc" />
        <File name="IcnsImagePlugin" src="libs/PIL/IcnsImagePlugin.py" />
        <File name="IcnsImagePlugin" src="libs/PIL/IcnsImagePlugin.pyc" />
        <File name="IcoImagePlugin" src="libs/PIL/IcoImagePlugin.py" />
        <File name="IcoImagePlugin" src="libs/PIL/IcoImagePlugin.pyc" />
        <File name="ImImagePlugin" src="libs/PIL/ImImagePlugin.py" />
        <File name="ImImagePlugin" src="libs/PIL/ImImagePlugin.pyc" />
        <File name="Image" src="libs/PIL/Image.py" />
        <File name="Image" src="libs/PIL/Image.pyc" />
        <File name="ImageChops" src="libs/PIL/ImageChops.py" />
        <File name="ImageChops" src="libs/PIL/ImageChops.pyc" />
        <File name="ImageCms" src="libs/PIL/ImageCms.py" />
        <File name="ImageCms" src="libs/PIL/ImageCms.pyc" />
        <File name="ImageColor" src="libs/PIL/ImageColor.py" />
        <File name="ImageColor" src="libs/PIL/ImageColor.pyc" />
        <File name="ImageDraw" src="libs/PIL/ImageDraw.py" />
        <File name="ImageDraw" src="libs/PIL/ImageDraw.pyc" />
        <File name="ImageDraw2" src="libs/PIL/ImageDraw2.py" />
        <File name="ImageDraw2" src="libs/PIL/ImageDraw2.pyc" />
        <File name="ImageEnhance" src="libs/PIL/ImageEnhance.py" />
        <File name="ImageEnhance" src="libs/PIL/ImageEnhance.pyc" />
        <File name="ImageFile" src="libs/PIL/ImageFile.py" />
        <File name="ImageFile" src="libs/PIL/ImageFile.pyc" />
        <File name="ImageFilter" src="libs/PIL/ImageFilter.py" />
        <File name="ImageFilter" src="libs/PIL/ImageFilter.pyc" />
        <File name="ImageFont" src="libs/PIL/ImageFont.py" />
        <File name="ImageFont" src="libs/PIL/ImageFont.pyc" />
        <File name="ImageGrab" src="libs/PIL/ImageGrab.py" />
        <File name="ImageGrab" src="libs/PIL/ImageGrab.pyc" />
        <File name="ImageMath" src="libs/PIL/ImageMath.py" />
        <File name="ImageMath" src="libs/PIL/ImageMath.pyc" />
        <File name="ImageMode" src="libs/PIL/ImageMode.py" />
        <File name="ImageMode" src="libs/PIL/ImageMode.pyc" />
        <File name="ImageMorph" src="libs/PIL/ImageMorph.py" />
        <File name="ImageMorph" src="libs/PIL/ImageMorph.pyc" />
        <File name="ImageOps" src="libs/PIL/ImageOps.py" />
        <File name="ImageOps" src="libs/PIL/ImageOps.pyc" />
        <File name="ImagePalette" src="libs/PIL/ImagePalette.py" />
        <File name="ImagePalette" src="libs/PIL/ImagePalette.pyc" />
        <File name="ImagePath" src="libs/PIL/ImagePath.py" />
        <File name="ImagePath" src="libs/PIL/ImagePath.pyc" />
        <File name="ImageQt" src="libs/PIL/ImageQt.py" />
        <File name="ImageQt" src="libs/PIL/ImageQt.pyc" />
        <File name="ImageSequence" src="libs/PIL/ImageSequence.py" />
        <File name="ImageSequence" src="libs/PIL/ImageSequence.pyc" />
        <File name="ImageShow" src="libs/PIL/ImageShow.py" />
        <File name="ImageShow" src="libs/PIL/ImageShow.pyc" />
        <File name="ImageStat" src="libs/PIL/ImageStat.py" />
        <File name="ImageStat" src="libs/PIL/ImageStat.pyc" />
        <File name="ImageTk" src="libs/PIL/ImageTk.py" />
        <File name="ImageTk" src="libs/PIL/ImageTk.pyc" />
        <File name="ImageTransform" src="libs/PIL/ImageTransform.py" />
        <File name="ImageTransform" src="libs/PIL/ImageTransform.pyc" />
        <File name="ImageWin" src="libs/PIL/ImageWin.py" />
        <File name="ImageWin" src="libs/PIL/ImageWin.pyc" />
        <File name="ImtImagePlugin" src="libs/PIL/ImtImagePlugin.py" />
        <File name="ImtImagePlugin" src="libs/PIL/ImtImagePlugin.pyc" />
        <File name="IptcImagePlugin" src="libs/PIL/IptcImagePlugin.py" />
        <File name="IptcImagePlugin" src="libs/PIL/IptcImagePlugin.pyc" />
        <File name="Jpeg2KImagePlugin" src="libs/PIL/Jpeg2KImagePlugin.py" />
        <File name="Jpeg2KImagePlugin" src="libs/PIL/Jpeg2KImagePlugin.pyc" />
        <File name="JpegImagePlugin" src="libs/PIL/JpegImagePlugin.py" />
        <File name="JpegImagePlugin" src="libs/PIL/JpegImagePlugin.pyc" />
        <File name="JpegPresets" src="libs/PIL/JpegPresets.py" />
        <File name="JpegPresets" src="libs/PIL/JpegPresets.pyc" />
        <File name="McIdasImagePlugin" src="libs/PIL/McIdasImagePlugin.py" />
        <File name="McIdasImagePlugin" src="libs/PIL/McIdasImagePlugin.pyc" />
        <File name="MicImagePlugin" src="libs/PIL/MicImagePlugin.py" />
        <File name="MicImagePlugin" src="libs/PIL/MicImagePlugin.pyc" />
        <File name="MpegImagePlugin" src="libs/PIL/MpegImagePlugin.py" />
        <File name="MpegImagePlugin" src="libs/PIL/MpegImagePlugin.pyc" />
        <File name="MpoImagePlugin" src="libs/PIL/MpoImagePlugin.py" />
        <File name="MpoImagePlugin" src="libs/PIL/MpoImagePlugin.pyc" />
        <File name="MspImagePlugin" src="libs/PIL/MspImagePlugin.py" />
        <File name="MspImagePlugin" src="libs/PIL/MspImagePlugin.pyc" />
        <File name="PSDraw" src="libs/PIL/PSDraw.py" />
        <File name="PSDraw" src="libs/PIL/PSDraw.pyc" />
        <File name="PaletteFile" src="libs/PIL/PaletteFile.py" />
        <File name="PaletteFile" src="libs/PIL/PaletteFile.pyc" />
        <File name="PalmImagePlugin" src="libs/PIL/PalmImagePlugin.py" />
        <File name="PalmImagePlugin" src="libs/PIL/PalmImagePlugin.pyc" />
        <File name="PcdImagePlugin" src="libs/PIL/PcdImagePlugin.py" />
        <File name="PcdImagePlugin" src="libs/PIL/PcdImagePlugin.pyc" />
        <File name="PcfFontFile" src="libs/PIL/PcfFontFile.py" />
        <File name="PcfFontFile" src="libs/PIL/PcfFontFile.pyc" />
        <File name="PcxImagePlugin" src="libs/PIL/PcxImagePlugin.py" />
        <File name="PcxImagePlugin" src="libs/PIL/PcxImagePlugin.pyc" />
        <File name="PdfImagePlugin" src="libs/PIL/PdfImagePlugin.py" />
        <File name="PdfImagePlugin" src="libs/PIL/PdfImagePlugin.pyc" />
        <File name="PdfParser" src="libs/PIL/PdfParser.py" />
        <File name="PdfParser" src="libs/PIL/PdfParser.pyc" />
        <File name="PixarImagePlugin" src="libs/PIL/PixarImagePlugin.py" />
        <File name="PixarImagePlugin" src="libs/PIL/PixarImagePlugin.pyc" />
        <File name="PngImagePlugin" src="libs/PIL/PngImagePlugin.py" />
        <File name="PngImagePlugin" src="libs/PIL/PngImagePlugin.pyc" />
        <File name="PpmImagePlugin" src="libs/PIL/PpmImagePlugin.py" />
        <File name="PpmImagePlugin" src="libs/PIL/PpmImagePlugin.pyc" />
        <File name="PsdImagePlugin" src="libs/PIL/PsdImagePlugin.py" />
        <File name="PsdImagePlugin" src="libs/PIL/PsdImagePlugin.pyc" />
        <File name="PyAccess" src="libs/PIL/PyAccess.py" />
        <File name="PyAccess" src="libs/PIL/PyAccess.pyc" />
        <File name="SgiImagePlugin" src="libs/PIL/SgiImagePlugin.py" />
        <File name="SgiImagePlugin" src="libs/PIL/SgiImagePlugin.pyc" />
        <File name="SpiderImagePlugin" src="libs/PIL/SpiderImagePlugin.py" />
        <File name="SpiderImagePlugin" src="libs/PIL/SpiderImagePlugin.pyc" />
        <File name="SunImagePlugin" src="libs/PIL/SunImagePlugin.py" />
        <File name="SunImagePlugin" src="libs/PIL/SunImagePlugin.pyc" />
        <File name="TarIO" src="libs/PIL/TarIO.py" />
        <File name="TarIO" src="libs/PIL/TarIO.pyc" />
        <File name="TgaImagePlugin" src="libs/PIL/TgaImagePlugin.py" />
        <File name="TgaImagePlugin" src="libs/PIL/TgaImagePlugin.pyc" />
        <File name="TiffImagePlugin" src="libs/PIL/TiffImagePlugin.py" />
        <File name="TiffImagePlugin" src="libs/PIL/TiffImagePlugin.pyc" />
        <File name="TiffTags" src="libs/PIL/TiffTags.py" />
        <File name="TiffTags" src="libs/PIL/TiffTags.pyc" />
        <File name="WalImageFile" src="libs/PIL/WalImageFile.py" />
        <File name="WalImageFile" src="libs/PIL/WalImageFile.pyc" />
        <File name="WebPImagePlugin" src="libs/PIL/WebPImagePlugin.py" />
        <File name="WebPImagePlugin" src="libs/PIL/WebPImagePlugin.pyc" />
        <File name="WmfImagePlugin" src="libs/PIL/WmfImagePlugin.py" />
        <File name="WmfImagePlugin" src="libs/PIL/WmfImagePlugin.pyc" />
        <File name="XVThumbImagePlugin" src="libs/PIL/XVThumbImagePlugin.py" />
        <File name="XVThumbImagePlugin" src="libs/PIL/XVThumbImagePlugin.pyc" />
        <File name="XbmImagePlugin" src="libs/PIL/XbmImagePlugin.py" />
        <File name="XbmImagePlugin" src="libs/PIL/XbmImagePlugin.pyc" />
        <File name="XpmImagePlugin" src="libs/PIL/XpmImagePlugin.py" />
        <File name="XpmImagePlugin" src="libs/PIL/XpmImagePlugin.pyc" />
        <File name="__init__" src="libs/PIL/__init__.py" />
        <File name="__init__" src="libs/PIL/__init__.pyc" />
        <File name="__main__" src="libs/PIL/__main__.py" />
        <File name="__main__" src="libs/PIL/__main__.pyc" />
        <File name="_binary" src="libs/PIL/_binary.py" />
        <File name="_binary" src="libs/PIL/_binary.pyc" />
        <File name="_imaging" src="libs/PIL/_imaging.pyd" />
        <File name="_imagingcms" src="libs/PIL/_imagingcms.pyd" />
        <File name="_imagingft" src="libs/PIL/_imagingft.pyd" />
        <File name="_imagingmath" src="libs/PIL/_imagingmath.pyd" />
        <File name="_imagingmorph" src="libs/PIL/_imagingmorph.pyd" />
        <File name="_imagingtk" src="libs/PIL/_imagingtk.pyd" />
        <File name="_tkinter_finder" src="libs/PIL/_tkinter_finder.py" />
        <File name="_tkinter_finder" src="libs/PIL/_tkinter_finder.pyc" />
        <File name="_util" src="libs/PIL/_util.py" />
        <File name="_util" src="libs/PIL/_util.pyc" />
        <File name="_version" src="libs/PIL/_version.py" />
        <File name="_version" src="libs/PIL/_version.pyc" />
        <File name="_webp" src="libs/PIL/_webp.pyd" />
        <File name="features" src="libs/PIL/features.py" />
        <File name="features" src="libs/PIL/features.pyc" />
        <File name="INSTALLER" src="libs/Pillow-6.2.2.dist-info/INSTALLER" />
        <File name="LICENSE" src="libs/Pillow-6.2.2.dist-info/LICENSE" />
        <File name="METADATA" src="libs/Pillow-6.2.2.dist-info/METADATA" />
        <File name="RECORD" src="libs/Pillow-6.2.2.dist-info/RECORD" />
        <File name="WHEEL" src="libs/Pillow-6.2.2.dist-info/WHEEL" />
        <File name="top_level" src="libs/Pillow-6.2.2.dist-info/top_level.txt" />
        <File name="zip-safe" src="libs/Pillow-6.2.2.dist-info/zip-safe" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
